# Generated by Django 4.1.2 on 2022-10-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_ayada_employee_area'),
        ('clinics', '0002_category_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='ayada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ayadat', verbose_name='العيادة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='specific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.specific', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.category', verbose_name='تخصص العيادة'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='day',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ اليوم'),
        ),
    ]
