# Generated by Django 4.1.2 on 2022-10-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_dailyreport_ayada_alter_category_specific_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='day',
            field=models.DateField(auto_now_add=True, null=True, unique=True, verbose_name='تاريخ اليوم'),
        ),
    ]
