# Generated by Django 4.0.6 on 2022-11-10 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_alter_dailyreporthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ اليوم'),
        ),
    ]
