# Generated by Django 4.1.3 on 2022-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_dailyreporthistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='ayadaSlug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='categorySlug',
            field=models.SlugField(null=True),
        ),
    ]
