# Generated by Django 4.1.2 on 2022-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='price',
            field=models.IntegerField(default=0, verbose_name='الرسوم المقررة'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='by_doctor',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_by',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.CharField(default='-', max_length=50, verbose_name='وصف الحالة'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='diagnosis',
            field=models.CharField(default='-', max_length=50, verbose_name='التشخيص'),
        ),
    ]
