# Generated by Django 4.0.6 on 2022-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
