# Generated by Django 4.1.2 on 2022-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_letter_price_alter_letter_by_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.service', verbose_name='الخدمات'),
        ),
    ]
