# Generated by Django 4.1.2 on 2022-10-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_letter_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='ayada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_law', to='services.ayadat', verbose_name='العيادة المحول منها'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='by_doctor',
            field=models.CharField(max_length=50, verbose_name='مقرر الإجراء'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_by',
            field=models.CharField(default='-', max_length=50, verbose_name='مسئول التسجيل'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_entity', to='services.entity', verbose_name='الجهة'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='law',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_law', to='services.law', verbose_name='قانون الانتفاع'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='naId',
            field=models.CharField(max_length=14, verbose_name='الرقم القومى'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم المريض ثلاثى'),
        ),
    ]
