# Generated by Django 4.0.6 on 2022-10-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Area',
            new_name='area',
        ),
    ]
