# Generated by Django 4.1.2 on 2022-10-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_area_employee_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ayada', to='services.ayadat'),
        ),
    ]
