# Generated by Django 4.1.2 on 2022-10-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_employee_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='area',
            new_name='ayada',
        ),
    ]
