# Generated by Django 4.0.6 on 2022-10-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_entity_name_alter_entitymainclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='mainClass',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_main', to='services.entitymainclass', verbose_name='التصنيف الرئيسى'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='subClass',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_sub', to='services.entitysubclass', verbose_name='التصنيف الفرعى'),
        ),
    ]
