# Generated by Django 4.0.6 on 2022-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_entity_mainclass_alter_entity_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityservice',
            name='services',
            field=models.ManyToManyField(default='-', null=True, related_name='services_entity', to='services.service'),
        ),
    ]
