# Generated by Django 4.0.6 on 2022-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_entityservice_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityservice',
            name='services',
            field=models.ManyToManyField(default='-', related_name='services_entity', to='services.service'),
        ),
    ]
