# Generated by Django 4.0.6 on 2022-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_entityservice_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.TextField(default='-', max_length=50, verbose_name='وصف الحالة'),
        ),
        migrations.AlterField(
            model_name='servicesubclass',
            name='name',
            field=models.CharField(db_index=True, default='-', max_length=100, verbose_name='التصنيف الفرعى'),
        ),
    ]
