# Generated by Django 4.0.6 on 2022-10-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_letter_description_alter_servicesubclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.TextField(default='-', max_length=250, verbose_name='وصف الحالة'),
        ),
    ]
