# Generated by Django 4.0.6 on 2022-10-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_letter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='area2',
            field=models.ManyToManyField(related_name='employee_ayadat', to='services.ayadat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_ayada', to='services.ayadat'),
        ),
    ]
