# Generated by Django 4.0.6 on 2022-11-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_employee_area2_alter_employee_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.TextField(default=' ', max_length=250, verbose_name='وصف الحالة'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='diagnosis',
            field=models.CharField(default=' ', max_length=50, verbose_name='التشخيص'),
        ),
    ]
