# Generated by Django 4.0.6 on 2022-11-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_letter_description_alter_letter_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='serial',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
