# Generated by Django 4.0.6 on 2022-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_letter_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, default='-', max_length=250, verbose_name='اسم الخدمة'),
        ),
    ]
