# Generated by Django 4.1.3 on 2022-11-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
