# Generated by Django 4.1.3 on 2022-11-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_letter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='cancelReason',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
