# Generated by Django 4.1.3 on 2022-11-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_letter_cancelreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('price', models.IntegerField(default=0, verbose_name='الرسوم المقررة')),
                ('notes', models.CharField(default=' ', max_length=50, verbose_name='ملاحظات')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='services.service', verbose_name='اسم الخدمة')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
