"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import pytz

from datetime import datetime, timedelta

## time zone +1 as the daysavelight
# Define the Cairo time zone with DST
cairo_tz = pytz.timezone('Africa/Cairo')

# Define the DST transition dates for Cairo
# Note: These dates may change in future years, so you may need to update them accordingly
cairo_dst_start = datetime(2023, 4, 28, 0, 0, tzinfo=cairo_tz)
cairo_dst_end = datetime(2023, 9, 1, 0, 0, tzinfo=cairo_tz)

# Define a custom time zone object that includes DST transitions for Cairo
class CairoTimezone(pytz.tzinfo.BaseTzInfo):
    def utcoffset(self, dt):
        return timedelta(hours=2) + self.dst(dt)

    def dst(self, dt):
        if cairo_dst_start <= dt.replace(tzinfo=None) < cairo_dst_end:
            return timedelta(hours=1)
        else:
            return timedelta(0)

    def tzname(self, dt):
        return 'EET' if not self.dst(dt) else 'EEST'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h0#m!yvgyn3wommq@r7r-9itd)7$+u*5rrc^q$chvm(b+lf8($'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'bootstrap4',
    'import_export',
    'corsheaders',
    'rest_framework',
	'services',
    'clinics'
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'
LOGIN_REDIRECT_URL = '/clinics/profile'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# variables to be changed to work on localhost or online in pythonanywhere
dataBaseName = "test"
dataBaseUser = "hio"
password     = "vr^*6QgT"
host         = "hio.mysql.pythonanywhere-services.com"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hio$hio',
        'USER': 'hio',
        'PASSWORD': 'vr^*6QgT',
        'HOST': "hio.mysql.pythonanywhere-services.com",
        'PORT':'3306',
        'OPTIONS': {
            'sql_mode': 'traditional',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Set the TIME_ZONE variable to the name of the Cairo time zone
TIME_ZONE = 'Africa/Cairo'

# Replace the default time zone with a custom time zone object that includes DST transitions for Cairo
pytz.timezone = lambda name: CairoTimezone() if name == 'Africa/Cairoo' else pytz.timezone(name)


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

localPath = "/home/hio/hio_project"
# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = localPath +'/media/'
MEDIA_URL = 'media/'
STATIC_ROOT = localPath+'/static/'
STATIC_URL = '/static/'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True